course_name = "理学类跨专业课程"
course_code = "Cross-Science"
repo_type = "multi-project"
description = "本仓库包含理学院开设的数理类跨专业课程。"

[[courses]]
name = "数智结构概论"

[[courses.teachers]]
name = "蔡坤"

[[courses.teachers.reviews]]
content = "是一个有点保守的老师，用他自己的话来说也有点说什么比较不顾忌。上课时要注意保持本心，培养辩证思维能力（doge）。"

[[courses.sections]]
title = "课程概况"

[[courses.sections.items]]
content = """
- 每节课考勤，形式为课前扫码签到。按理来说可以签完到就溜，但是老师后面会有抽签提问环节，要是抽到了不在那节课考勤就算不在。
- 课程形式是上半节讲内容，下半节看视频，然后最后几分钟会根据视频内容提问。每节课都有课后作业，下星期的那天交，内容也是跟视频内容相关，大家大部分都是用电脑写好打印出来提交（因为真的很多）。
- 给分比较宽松，考勤和作业没问题的话都能过，我是A，不过好像作业有一定次数没交老师就会让助教挂你的科。
- 因为种种原因（老师体验感不太好），这门课貌似已成为绝版课程，个人觉得挺可惜，毕竟三分好水的跨专业也不多。
"""
author = { name = "SpeechlessPanda", link = "https://github.com/SpeechlessPanda", date = "2026-01" }

[[courses]]
name = "电动力学"

[[courses.teachers]]
name = "秦刚"

[[courses.sections]]
title = "课程概况"

[[courses.sections.items]]
content = """
- 每节课会有遍历点名，但是不会以此挂人。上课颇为硬核，且老师语速慢，吐字比较不清晰，所以很难听懂。
- 有四次作业，但是很简单，且此四次作业能决定大部分平时分。
- 24 春期末考为全选填，25 春期末考是五题大题，每道大题都是一个概念的简述，考试内容限于大物电磁学部分，具体可以见资料下载，捞的很狠（最后应该是零人挂科）。
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-07" }

[[courses]]
name = "量子力学"

[[courses.teachers]]
name = "邓皓键"

[[courses.teachers.reviews]]
content = """
老师很友好，但是普通话有点不好，类似于外国人说中文，但是能听懂。
上课使用长江雨课堂点名，还会让助教在八点十分左右进行签到。课上不会管你在做什么，但是期末专门认识了几个听课比较认真的同学。
每节课进行板书，没有 PPT。前面部分和教材基本符合，后面量子计算没有教材，但是难度较低一点。期末考试，听讲＋做好作业很好过。
"""
author = { name = "Layaka", link = "", date = "2025-12" }

[[courses.sections]]
title = "关于考试"

[[courses.sections.items]]
content = """
2025 年秋季学期考试内容：

第一题，希尔伯特空间相关内容

第二题，波函数相关，归一化和波函数到概率密度

第三题，势垒问题

第四题，势阱问题

第五题，氢原子的物理量 nlm

第六题，量子计算，boch 球相关
"""
author = { name = "Layaka", link = "", date = "2025-12" }

[[courses]]
name = "走进量子世界"

[[courses.teachers]]
name = "周宇"

[[courses.sections]]
title = "课程概况"

[[courses.sections.items]]
content = """
- 这一门正如老师自己所说：就是一门福利课。四学分的跨专业课不费吹灰之力。
- 平时有小测和考勤，但是可以不用管，不扣平时分（因为根本就没有）。
- 课堂汇报只要是和量子力学相关的内容基本都是 30 分 / 29 分。
- 实验可以使用 AI，交了实验报告就是 20 分。
- 最后卷面 100 分折算成50分的考试也非常容易，老师最后会发两份PDF，只需要对着PDF里面的内容复习即可，掌握量子力学历史、布洛赫球、简单的量子计算就可以轻松过关。
"""
author = { name = "潜伏", link = "https://github.com/capoo-fan", date = "2026-01" }

[[courses]]
name = "理论力学"

[[courses.teachers]]
name = "凡友华、蔡坤"

[[courses.sections]]
title = "课程概况"

[[courses.sections.items]]
content = """
这一门课是比较硬核的力学课程，包括运动学、静力学和动力学，涉及了很多新的物理概念。作业题难度有点大，但如果能认真听老师讲解的例题以及善于使用工具的话也不是问题（画图很重要！）

虽然如此，考试非常简单。大部分直接考察基本概念，小部分计算题也不涉及复杂的分析，只需要套公式就可以（别被课本上复杂的例题吓到）。考试内容包括基础的运动学、刚体的复合运动、基础的静力学、刚体动力学、虚功原理、拉格朗日方程。只要掌握最基础的概念和公式，过这门四学分的跨专业课就不难。

没有考勤和汇报！
"""
author = { name = "lpf", link = "https://github.com/lpf123321", date = "2026-02" }

[[courses]]
name = "大学化学III"

[[courses.sections]]
title = "课程概况"

[[courses.sections.items]]
content = """
开课期间要求学生在 3 个模块中各选择一个化学实验完成，每个时长在 3 学时左右。难度整体都一般，还是挺有意思的（在本科期间有多少机会进入化学实验室呢？）。

没有期末考试，这是这门课对学生最友好的一点，学习压力会小很多。

总的来说，占用时间精力很少，性价比还是很高的。
"""
author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "2023-09" }

[[courses]]
name = "波谱学原理与应用"

[[courses.teachers]]
name = "杨超"

[[courses.sections]]
title = "课程概况"

[[courses.sections.items]]
content = """
- 上课不考勤，偶尔会按点名表顺序抽人回答问题~~在后面的完全不用担心~~，但是习题课一定要去！
- 考试难度不大，老师上课很认真很亲切，讲解也很清楚，如果认真听的话一定可以学到东西。
- ppt 全英文且课后不发放ppt，期末考看 B 站的波谱学速成视频就够了。
- 课程作业每次只有一道题，上交方式为 QQ 群小程序上交。10min 可解决。
- 课程 pre 在每一小章节结束后的习题课上，形式为微信小程序“ OS.波谱学原理与应用”中的对应习题（按点名表序号选题）有半个小时的作答时间，只要讲出分析思路即可（1min 左右）~~实测用 AI 完全可以做完~~
"""
author = { name = "lumen", link = "https://github.com/lumen183", date = "2026-01" }

[[courses.sections]]
title = "关于考试"

[[courses.sections.items]]
content = """
2025 年秋季学期考试内容：

选择题： 20 题，每题 1 分。

其余为解答题，分布为：

谐振子模型估算红外吸收峰

给定结构和紫外吸收波长，判断物质

给定红外吸收峰，判断物质

紫外，红外，质谱仪综合应用。
"""
author = { name = "lumen", link = "https://github.com/lumen183", date = "2026-01" }

[[courses]]
name = "生物学导论"

[[courses.sections]]
title = "课程概况"

[[courses.sections.items]]
content = """
- 每个章节讲完后有小测，小测题量较大，使用搜题也要半小时，也有当成作业过。
- 只有一次签到且用小测代替。
- 课程汇报只要和生物学相关即可，PPT 20 页左右即可。
- 给分较宽松，大部分人都有 80+ 甚至 90+
"""
author = { name = "海边的星空", link = "https://", date = "2025-01" }

[[courses]]
name = "动力学与控制基础"

[[courses.teachers]]
name = "陈立群"

[[courses.sections]]
title = "课程概况"

[[courses.sections.items]]
content = """
- 无考勤，无考试，无实验，只有几次作业和最后有一个课程论文。非常好过。
- 给分也很慷慨，都交了就有90分。
"""
author = { name = "SpeechlessPanda", link = "https://github.com/SpeechlessPanda", date = "2026-06" }
